required = [
    "github.com/vektra/mockery/cmd/mockery",
    "github.com/golang/protobuf/protoc-gen-go",
]

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[prune]
  go-tests = true
  unused-packages = true
