// Code generated by mockery v1.0.0. DO NOT EDIT.

package mock

import mock "github.com/stretchr/testify/mock"
import time "time"

// Together is an autogenerated mock type for the Together type
type Together struct {
	mock.Mock
}

// SpendPercentage provides a mock function with given fields: number1, number2, from, to, distance
func (_m *Together) SpendPercentage(number1 string, number2 string, from time.Time, to time.Time, distance int) (int, error) {
	ret := _m.Called(number1, number2, from, to, distance)

	var r0 int
	if rf, ok := ret.Get(0).(func(string, string, time.Time, time.Time, int) int); ok {
		r0 = rf(number1, number2, from, to, distance)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, time.Time, time.Time, int) error); ok {
		r1 = rf(number1, number2, from, to, distance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
