// Code generated by mockery v1.0.0. DO NOT EDIT.

package mock

import mock "github.com/stretchr/testify/mock"
import model "github.com/devchallenge/spy-api/internal/model"

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// Read provides a mock function with given fields: number
func (_m *Storage) Read(number string) ([]model.Together, error) {
	ret := _m.Called(number)

	var r0 []model.Together
	if rf, ok := ret.Get(0).(func(string) []model.Together); ok {
		r0 = rf(number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Together)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
